addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.5")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.9")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "2.1.1")
